# config.yaml
host:
  name: "chuk-mcp-runtime"
  log_level: "INFO"

server:
  type: "sse"
  auth: "bearer" # this line is needed to enable bearer auth

# optional overrides
sse:
  host: "0.0.0.0"
  port: 8000
  sse_path: "/sse"
  message_path: "/messages/"
  log_level: "info"
  access_log: true

proxy:
  enabled: false
  namespace: "proxy"
  openai_compatible: false   # ‚Üê set to true if you want underscores

mcp_servers:
  time:
    type: "stdio"
    command: "uvx"
    args: ["mcp-server-time", "--local-timezone", "America/New_York"]
  echo:
    enabled: true
    location: "../mcp-echo-server/src"
    tools:
      enabled: true
      module: "mcp_echo_server.echo_tools.tools"